// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtiDy8HSr3A4NXsdDqIPB6RQZvdb6JJ04',
    appId: '1:225339067618:web:1871755cb2584c18e5e2bb',
    messagingSenderId: '225339067618',
    projectId: 'todo-rapip',
    authDomain: 'todo-rapip.firebaseapp.com',
    storageBucket: 'todo-rapip.firebasestorage.app',
    measurementId: 'G-BW6C7LN0BM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAU28pw8FgbKrgeqGzEynhNN-t6_Ojl10',
    appId: '1:225339067618:android:035364d2cd2ca5fde5e2bb',
    messagingSenderId: '225339067618',
    projectId: 'todo-rapip',
    storageBucket: 'todo-rapip.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByC2uTE8FUhdz8UAS10FOzFwzw2aGSrGA',
    appId: '1:225339067618:ios:d27e90f12eae613ee5e2bb',
    messagingSenderId: '225339067618',
    projectId: 'todo-rapip',
    storageBucket: 'todo-rapip.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );
}
